---
title: Data Management Plan
subtitle: Survey 
lang: en
# author:
#   - name: Julian Bashir
#     email: jbashir@starfleet.ufp
#     orcid: 0000-0000-0000-0000
#     title: Chief Medical Officer
#     affiliations: 
#       - id: ds9
#         name: Starbase Deep Space Nine
#         department: Sick Bay
#         address: 1234 Main Street
#         city: Anytown
#         region: NY
#         country: USA
#         postal-code: 90210
#     attributes:
#       corresponding: true
#   - name: Elim Garak
#     email: tailor.spy@obsidianorder.card.gov
#     title: Shopkeeper and Tailor
#     affiliations:
#       - id: terok
#         name: Terok Nor
#         department: Promenade
#       - ref: ds9
# date: August 24, 2022
bibliography: refs.bib
format: 
  moobyf-docx: default
---

## DATESET list in DMP v1

-   DATASET-01 Video files from embarked cameras (video)
-   DATASET-02 Deep learning models and training datasets applied on the videos (models, dataset);
-   DATASET-03 Surveys of fishers, local ecological knowledge and associated cultural values (dataset);
-   DATASET-04 Local reference DNA sequence database for genetic analyses(dataset);
-   DATASET-05List of species found through meta-barcoding (stomach contents) (dataset);
-   DATASET-06 List of species found through meta-barcoding (eDNA) (dataset);
-   DATASET-07 NetCDF files of bioacoustic data (dataset);
-   DATASET-08 Deep learning models and training datasetsapplied on the bioacoustic data(models, dataset);
-   DATASET-09 NetCDF files of echosounder buoys data (dataset);
-   DATASET-10 NetCDF files of WBAT echosounder data (dataset);

## Dataset listing

Could you list for each WP the following informations ?

-   The list of dataset you will have
-   Where the data are stored during the research process (IRD Drive, MARBEC-DATA, laptop ...) ?

Fo each datasets :

a.  How will new data be collected or produced and/or how will existing data be re-used?
b.  What data (for example the kind, formats, and volumes) will be collected or produced?

-   Explain which methodologies or software will be used if new data are collected or produced. Explain how data provenance will be documented.
-   Give details on the kind of data: for example, numeric (databases, spreadsheets), textual documents or image. Give details on the data format: the way in which the data is encoded for storage, often reflected by the filename extension. Give preference to open and standard formats.
-   Give details on the volumes.
-   Do you know which metadata standard that we need to describe the data collected ?

# Data identifiers

## Unique Site Identifiers

We need to define an ID for site in purpose to keep on track our data and the sample. I propose somthing based on MT + CC + ST. What else is interesting to add ?

| USID | Description    |
|------|----------------|
| MT   | Methodoology   |
| CC   | Country Code   |
| TS   | Targeted Site  |

: Components of the Unique Site ID

| Methodology  | Code |
|--------------|------|
| bioacoustics | BA   |
|              |      |

: Country Codes for samples

| Country   | ISO 3166-1 Alpha-3 |
|-----------|--------------------|
| Indonesia | IDN                |
| Mayotte   | MYT                |
| Maldives  | MDV                |
|           |                    |

: Country Codes for samples



| Targeted site  | Site code |
|----------------|-----------|
| Gondol         |           |
| Captive fish   |           |
| FAD1 in Pancer | F1P       |


: Site used as case studies

## Sampling naming conventions

A proposition is to adopt a name of the folders based on the USID defined above, for example:

BA_IDN_F1P_Q1_S1 where S1 is the sample number (it can be for example a depth where we put an idrophone, or a camera number) Then, we would have a metadata table (one per methodology, for example, one table for BA=bioacoustics), with the following info (one column per item):

-   Folder_name
-   File name
-   Latitude
-   Longitude
-   Date
-   Depth (if relevant)
    -   all metadata relevant for the given methodology

If you are agree with that, could you fill the table above with your needs ?